-- Drop tables if they exist
DROP TABLE IF EXISTS pc CASCADE;
DROP TABLE IF EXISTS networking CASCADE;
DROP TABLE IF EXISTS cooling_system CASCADE;
DROP TABLE IF EXISTS casing CASCADE;
DROP TABLE IF EXISTS psu CASCADE;
DROP TABLE IF EXISTS hdd CASCADE;
DROP TABLE IF EXISTS ssd CASCADE;
DROP TABLE IF EXISTS ram CASCADE;
DROP TABLE IF EXISTS motherboard CASCADE;
DROP TABLE IF EXISTS gpu CASCADE;
DROP TABLE IF EXISTS cpu CASCADE;

-- Create CPU table
CREATE TABLE cpu (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    make VARCHAR(64) NOT NULL,            -- e.g., Intel, AMD
    model VARCHAR(64) NOT NULL,           -- e.g., I5-12400F, Ryzen 7 5800X
    core_amount INT NOT NULL,
    thread_amount INT NOT NULL,
    clock_speed DOUBLE PRECISION NOT NULL,
    l3_size DOUBLE PRECISION NOT NULL,
    socket VARCHAR(64) NOT NULL,
    igpu VARCHAR(64),
    tdp INT NOT NULL
);

-- Create GPU table
CREATE TABLE gpu (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    make VARCHAR(64) NOT NULL,            -- e.g., NVIDIA, AMD
    model VARCHAR(64) NOT NULL,           -- e.g., RTX 3060, RX 6600
    vram_size INT NOT NULL,               -- in GB
    clock_speed INT NOT NULL,             -- in MHz
    mem_bus_width INT NOT NULL,           -- in bits
    has_hdmi BOOLEAN NOT NULL,
    has_dp BOOLEAN NOT NULL,
    has_usbc BOOLEAN NOT NULL,
    has_dvi BOOLEAN NOT NULL,
    has_vga BOOLEAN NOT NULL,
    power_consumption INT NOT NULL        -- in watts
);

-- Create Motherboard table
CREATE TABLE motherboard (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    make VARCHAR(64) NOT NULL,            -- e.g., ASUS, Gigabyte
    model VARCHAR(64) NOT NULL,           -- e.g., ROG Strix Z690-E
    form_factor VARCHAR(64) NOT NULL,     -- e.g., ATX, Micro-ATX
    socket VARCHAR(64) NOT NULL,
    chipset VARCHAR(64) NOT NULL,
    ram_slot_amount INT NOT NULL,
    ram_type VARCHAR(64) NOT NULL,
    pcie16_amount INT NOT NULL,
    pcie4_amount INT NOT NULL,
    pcie1_amount INT NOT NULL,
    m2_amount INT NOT NULL,
    sata_amount INT NOT NULL
);

-- Create RAM table
CREATE TABLE ram (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    make VARCHAR(64) NOT NULL,            -- e.g., Corsair, G.Skill
    model VARCHAR(64) NOT NULL,           -- e.g., Vengeance LPX, Trident Z RGB
    capacity INT NOT NULL,                -- in GB (per module)
    amount INT NOT NULL,                  -- number of modules
    ram_type VARCHAR(64) NOT NULL,
    clock INT NOT NULL                    -- in MHz
);

-- Create SSD table
CREATE TABLE ssd (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    make VARCHAR(64) NOT NULL,            -- e.g., Samsung, WD
    model VARCHAR(64) NOT NULL,           -- e.g., 970 EVO Plus, WD Blue
    capacity INT NOT NULL,                -- in GB
    type VARCHAR(64) NOT NULL,            -- e.g., SATA, NVMe
    form_factor VARCHAR(64) NOT NULL,     -- e.g., 2.5-inch, M.2 2280
    connection_interface VARCHAR(64) NOT NULL,  -- e.g., SATA III, PCIe 3.0 x4
    read_speed INT NOT NULL,              -- in MB/s
    write_speed INT NOT NULL,             -- in MB/s
    tbw INT                             -- Terabytes Written
);

-- Create HDD table
CREATE TABLE hdd (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    make VARCHAR(64) NOT NULL,            -- e.g., Seagate, WD
    model VARCHAR(64) NOT NULL,           -- e.g., Barracuda, WD Blue
    capacity INT NOT NULL,                -- in GB or TB
    rpm INT NOT NULL,
    cache_size INT NOT NULL,              -- in MB
    form_factor VARCHAR(64) NOT NULL,     -- e.g., 3.5-inch, 2.5-inch
    connection_interface VARCHAR(64) NOT NULL  -- e.g., SATA III
);

-- Create PSU table
CREATE TABLE psu (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    make VARCHAR(64) NOT NULL,            -- e.g., Corsair, EVGA
    model VARCHAR(64) NOT NULL,           -- e.g., RM550x, SuperNOVA 650 G5
    wattage INT NOT NULL,
    efficiency_rating VARCHAR(32),
    modularity VARCHAR(32) NOT NULL,
    connectors VARCHAR(256) NOT NULL,
    fan_size VARCHAR(32),
    cooling_type VARCHAR(32)
);

-- Create Casing table
CREATE TABLE casing (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    make VARCHAR(64) NOT NULL,            -- e.g., NZXT, Cooler Master
    model VARCHAR(64) NOT NULL,           -- e.g., H510, MasterBox Q300L
    form_factor VARCHAR(64) NOT NULL,     -- e.g., ATX, Micro-ATX, Mini-ITX
    material VARCHAR(64),
    cooling_support VARCHAR(256),
    expansion_slots INT NOT NULL,
    drive_bays_35 INT NOT NULL,
    drive_bays_25 INT NOT NULL,
    front_panel_ports VARCHAR(256),
    includes_rgb BOOLEAN NOT NULL
);

-- Create Cooling System table
CREATE TABLE cooling_system (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    make VARCHAR(64) NOT NULL,            -- e.g., Noctua, Corsair
    model VARCHAR(64) NOT NULL,           -- e.g., NH-U12S, H100i RGB Platinum
    type VARCHAR(64) NOT NULL,            -- e.g., Air Cooler, Liquid Cooler
    fan_size VARCHAR(32),
    radiator_size VARCHAR(32),
    noise_level VARCHAR(32),
    socket_compatibility VARCHAR(256) NOT NULL,
    tdp_support INT,
    includes_rgb BOOLEAN NOT NULL
);

-- Create Networking table
CREATE TABLE networking (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    make VARCHAR(64) NOT NULL,            -- e.g., Intel, TP-Link
    model VARCHAR(64) NOT NULL,           -- e.g., Wi-Fi 6 AX200, Archer TX3000E
    type VARCHAR(64) NOT NULL,            -- e.g., Wi-Fi Card, Ethernet Adapter
    connection_interface VARCHAR(64) NOT NULL,       -- e.g., PCIe, USB, M.2
    wifi_standard VARCHAR(32),
    ethernet_speed VARCHAR(32),
    antennas INT,
    bluetooth_version VARCHAR(32)
);

-- Create PC build table
CREATE TABLE pc (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL UNIQUE,
    cpu_id INT REFERENCES cpu(id),
    gpu_id INT REFERENCES gpu(id),
    motherboard_id INT REFERENCES motherboard(id),
    ram_id INT REFERENCES ram(id),
    ssd_id INT REFERENCES ssd(id),
    hdd_id INT REFERENCES hdd(id),
    psu_id INT REFERENCES psu(id),
    case_id INT REFERENCES casing(id),
    cooling_system_id INT REFERENCES cooling_system(id),
    networking_id INT REFERENCES networking(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-------------------------------------------------------
-- Insert Data
-------------------------------------------------------

-- Insert CPU data (existing and additional examples)
INSERT INTO cpu (make, model, core_amount, thread_amount, clock_speed, l3_size, socket, igpu, tdp) VALUES
  ('Intel', 'Core i5-12400F', 6, 12, 2.5, 18, 'LGA1700', NULL, 65),
  ('AMD', 'Ryzen 7 5800X', 8, 16, 3.8, 32, 'AM4', NULL, 105),
  ('Intel', 'Core i7-12700K', 12, 20, 3.6, 25, 'LGA1700', 'Intel UHD Graphics 770', 125),
  ('AMD', 'Ryzen 5 5600X', 6, 12, 3.7, 32, 'AM4', NULL, 65),
  ('AMD', 'Ryzen 5 5600G', 6, 12, 3.9, 16, 'AM4', 'Radeon Graphics', 65);

-- Insert GPU data (existing and additional examples)
INSERT INTO gpu (make, model, vram_size, clock_speed, mem_bus_width, has_hdmi, has_dp, has_usbc, has_dvi, has_vga, power_consumption) VALUES
  ('NVIDIA', 'RTX 3060', 12, 1807, 192, TRUE, TRUE, FALSE, FALSE, FALSE, 170),
  ('AMD', 'RX 6600 XT', 8, 1968, 128, TRUE, TRUE, FALSE, FALSE, FALSE, 160),
  ('NVIDIA', 'RTX 3080', 10, 1440, 320, TRUE, TRUE, FALSE, FALSE, FALSE, 320),
  ('AMD', 'Radeon RX 6800', 16, 1700, 256, TRUE, TRUE, FALSE, FALSE, FALSE, 250),
  ('NVIDIA', 'GTX 1660 Super', 6, 1530, 192, TRUE, TRUE, FALSE, FALSE, FALSE, 125);

-- Insert Motherboard data (existing and additional examples)
INSERT INTO motherboard (make, model, form_factor, socket, chipset, ram_slot_amount, ram_type, pcie16_amount, pcie4_amount, pcie1_amount, m2_amount, sata_amount) VALUES
  ('ASUS', 'ROG Strix Z690-E', 'ATX', 'LGA1700', 'Z690', 4, 'DDR5', 2, 1, 2, 3, 6),
  ('MSI', 'MPG B550 Gaming Edge', 'ATX', 'AM4', 'B550', 4, 'DDR4', 1, 1, 3, 2, 6),
  ('Gigabyte', 'X570 Aorus Elite', 'ATX', 'AM4', 'X570', 4, 'DDR4', 2, 2, 3, 2, 6),
  ('ASRock', 'B450M PRO4', 'Micro-ATX', 'AM4', 'B450', 4, 'DDR4', 1, 0, 2, 1, 4),
  ('ASUS', 'TUF Gaming X570-Plus', 'ATX', 'AM4', 'X570', 4, 'DDR4', 2, 1, 2, 2, 6);

-- Insert RAM data (existing and additional examples)
INSERT INTO ram (make, model, capacity, amount, ram_type, clock) VALUES
  ('Corsair', 'Vengeance LPX', 16, 2, 'DDR4', 3200),
  ('G.Skill', 'Trident Z RGB', 8, 4, 'DDR4', 3600),
  ('Corsair', 'Dominator Platinum', 16, 2, 'DDR5', 5200),
  ('Kingston', 'HyperX Fury', 8, 2, 'DDR4', 2666),
  ('G.Skill', 'Ripjaws V', 16, 2, 'DDR4', 3200);

-- Insert SSD data (existing and additional examples)
INSERT INTO ssd (make, model, capacity, type, form_factor, connection_interface, read_speed, write_speed, tbw) VALUES
  ('Samsung', '970 EVO Plus', 1000, 'NVMe', 'M.2 2280', 'PCIe 3.0 x4', 3500, 3300, 600),
  ('WD', 'Blue', 500, 'SATA', '2.5-inch', 'SATA III', 560, 530, 150),
  ('Crucial', 'MX500', 1000, 'SATA', '2.5-inch', 'SATA III', 560, 510, 360),
  ('Kingston', 'A2000', 500, 'NVMe', 'M.2 2280', 'PCIe 3.0 x4', 2000, 1100, 300),
  ('Samsung', '980 PRO', 1000, 'NVMe', 'M.2 2280', 'PCIe 4.0 x4', 7000, 5000, 600);

-- Insert HDD data (existing and additional examples)
INSERT INTO hdd (make, model, capacity, rpm, cache_size, form_factor, connection_interface) VALUES
  ('Seagate', 'Barracuda', 2000, 7200, 64, '3.5-inch', 'SATA III'),
  ('WD', 'Blue', 1000, 7200, 64, '3.5-inch', 'SATA III'),
  ('Toshiba', 'X300', 4000, 7200, 128, '3.5-inch', 'SATA III'),
  ('HGST', 'Deskstar NAS', 4000, 7200, 128, '3.5-inch', 'SATA III'),
  ('Seagate', 'IronWolf', 6000, 7200, 256, '3.5-inch', 'SATA III');

-- Insert PSU data (existing and additional examples)
INSERT INTO psu (make, model, wattage, efficiency_rating, modularity, connectors, fan_size, cooling_type) VALUES
  ('Corsair', 'RM550x', 550, '80+ Gold', 'Full', '24-pin, 8-pin CPU, 2x PCIe, 6+2 SATA', '120mm', 'Air'),
  ('EVGA', 'SuperNOVA 650 G5', 650, '80+ Gold', 'Full', '24-pin, 8-pin CPU, 3x PCIe, 8 SATA', '120mm', 'Air'),
  ('Seasonic', 'Focus GX-750', 750, '80+ Gold', 'Full', '24-pin, 8-pin CPU, 4x PCIe, 8 SATA', '120mm', 'Air'),
  ('Corsair', 'RM750x', 750, '80+ Gold', 'Full', '24-pin, 8-pin CPU, 2x PCIe, 8 SATA', '140mm', 'Air'),
  ('EVGA', 'SuperNOVA 850 G3', 850, '80+ Gold', 'Full', '24-pin, 8-pin CPU, 4x PCIe, 10 SATA', '120mm', 'Air');

-- Insert Casing data (existing and additional examples)
INSERT INTO casing (make, model, form_factor, material, cooling_support, expansion_slots, drive_bays_35, drive_bays_25, front_panel_ports, includes_rgb) VALUES
  ('NZXT', 'H510', 'ATX', 'Steel/Tempered Glass', 'Up to 360mm radiator', 7, 2, 2, 'USB 3.1, Audio In/Out', TRUE),
  ('Cooler Master', 'MasterBox Q300L', 'Micro-ATX', 'Plastic/Metal', 'Up to 240mm radiator', 6, 1, 2, 'USB 3.0, Audio', FALSE),
  ('Phanteks', 'Eclipse P400A', 'ATX', 'Steel/Tempered Glass', 'Up to 280mm radiator', 7, 2, 2, 'USB 3.0, USB-C, Audio', TRUE),
  ('Fractal Design', 'Meshify C', 'ATX', 'Steel/Tempered Glass', 'Up to 360mm radiator', 7, 2, 2, 'USB 3.0, Audio', FALSE),
  ('Corsair', 'iCUE 4000X RGB', 'ATX', 'Steel/Tempered Glass', 'Up to 360mm radiator', 7, 2, 2, 'USB 3.1, Audio, Microphone', TRUE);

-- Insert Cooling System data (existing and additional examples)
INSERT INTO cooling_system (make, model, type, fan_size, radiator_size, noise_level, socket_compatibility, tdp_support, includes_rgb) VALUES
  ('Noctua', 'NH-U12S', 'Air Cooler', '120mm', NULL, 'Low', 'LGA1700, AM4', 150, FALSE),
  ('Corsair', 'H100i RGB Platinum', 'Liquid Cooler', '120mm', '240mm', 'Medium', 'LGA1700, AM4', 250, TRUE),
  ('be quiet!', 'Dark Rock Pro 4', 'Air Cooler', '120mm', NULL, 'Very Low', 'LGA1200, LGA1151, AM4', 200, FALSE),
  ('Cooler Master', 'Hyper 212 EVO', 'Air Cooler', '120mm', NULL, 'Moderate', 'LGA1151, AM4', 150, FALSE),
  ('NZXT', 'Kraken Z63', 'Liquid Cooler', '140mm', '280mm', 'Low', 'LGA1700, AM4', 280, TRUE);

-- Insert Networking data (existing and additional examples)
INSERT INTO networking (make, model, type, connection_interface, wifi_standard, ethernet_speed, antennas, bluetooth_version) VALUES
  ('Intel', 'Wi-Fi 6 AX200', 'Wi-Fi Card', 'M.2', '802.11ax', NULL, 2, '5.1'),
  ('TP-Link', 'Archer TX3000E', 'Wi-Fi Card', 'PCIe', '802.11ax', NULL, 2, '5.0'),
  ('ASUS', 'XG-C100C', 'Ethernet Adapter', 'PCIe', NULL, '10Gbps', 0, NULL),
  ('Gigabyte', 'GC-WB867D', 'Wi-Fi Card', 'PCIe', '802.11ac', NULL, 2, '5.0'),
  ('Fenvi', 'T919', 'Wi-Fi Card', 'PCIe', '802.11ac', NULL, 2, '5.0');

-- Insert PC build data (existing and additional examples)
-- Note: The foreign key IDs here assume the insertion order above.
INSERT INTO pc (name, cpu_id, gpu_id, motherboard_id, ram_id, ssd_id, hdd_id, psu_id, case_id, cooling_system_id, networking_id) VALUES
  ('Gaming Beast', 3, 3, 1, 3, 1, 1, 3, 1, 2, 1),
  ('Workstation Pro', 2, 2, 3, 2, 3, 3, 2, 3, 3, 2),
  ('Budget Build', 1, 1, 2, 1, 2, 2, 1, 2, 1, 3),
  ('Ultimate Gamer', 5, 4, 4, 4, 4, 4, 4, 4, 4, 4),
  ('Office Workhorse', 1, 5, 2, 1, 2, 2, 1, 2, 1, 2),
  ('Content Creator', 3, 3, 1, 3, 5, 5, 5, 5, 5, 3),
  ('test buld', 1, 1, 1, 1, 1, 1, 1, 1, 1, 1);

SELECT
    p.id AS "PC ID",
    p.name AS "PC Name",
    c.make AS "CPU Make",
    g.make AS "GPU Make",
    m.chipset AS "Motherboard Chipset",
    r.make || ' ' || r.capacity || 'GB ' || r.ram_type AS "RAM",
    s.make || ' ' || s.capacity || 'GB ' || s.type AS "SSD",
    h.make || ' ' || h.capacity || 'GB' AS "HDD",
    ps.make AS "PSU Make",
    cs.make AS "Case Make",
    cl.make AS "Cooling System Make",
    n.make AS "Networking Make",
    p.created_at AS "Built On",
    p.updated_at AS "Updated At"
FROM pc p
JOIN cpu c ON p.cpu_id = c.id
JOIN gpu g ON p.gpu_id = g.id
JOIN motherboard m ON p.motherboard_id = m.id
JOIN ram r ON p.ram_id = r.id
JOIN ssd s ON p.ssd_id = s.id
JOIN hdd h ON p.hdd_id = h.id
JOIN psu ps ON p.psu_id = ps.id
JOIN casing cs ON p.case_id = cs.id
JOIN cooling_system cl ON p.cooling_system_id = cl.id
JOIN networking n ON p.networking_id = n.id;



